### ISSUE TITLE
No module named 'main' when running simulate.py

### ISSUE THREAD

**Issue by ParivashFeyzishendi** [KULL-Centre/_2023_Tesei_IDRome#1]
Hi, 
I encountered a ModuleNotFoundError when trying to run a script named simulate.py in the repository. The error occurs because the script attempts to import BlockAnalysis from a module named main, which does not seem to exist in the repository.

**Comment by gitesei** [comment]
Hi Parivash,
Thank you for your message. The script `simulate.py` in `md_simulations/code` requires a local copy of the [BLOCKING](https://github.com/fpesceKU/BLOCKING) code in the same folder as the script. BLOCKING can be downloaded from GitHub as in the following [snippet](https://github.com/KULL-Centre/_2023_Tesei_IDRome/blob/bee7ec54752bf2c114194814af4f4c55490b5295/md_simulations/code/submit.py#L37) in `md_simulations/code/submit.py`:

```python 
# Download blocking code
if not os.path.exists('BLOCKING'):
    subprocess.check_call(['git','clone','https://github.com/fpesceKU/BLOCKING'])
```
    
If anything is unclear or if you have any further questions, please let me know.
Kind regards,
Giulio
